#!/command/with-contenv bash
if ! [[ -d $HOME/.tinyssh ]]; then
	/usr/sbin/tinysshd-makekey -q "${HOME}/.tinyssh"
	chown -R qbittorrent:qbittorrent "${HOME}/.tinyssh"
fi

if ! [[ -d $HOME/.ssh ]]; then
	mkdir -p "${HOME}/.ssh"
	chown -R qbittorrent:qbittorrent "${HOME}/.ssh"
	chmod 0700 "${HOME}/.ssh"
fi

if [[ -z $SSH_PUBLIC_KEY ]]; then
	echo "!!! No public key defined. Please define one by setting the SSH_PUBLIC_KEY environment variable"
else
	echo -n "$SSH_PUBLIC_KEY" > "${HOME}/.ssh/authorized_keys"
	chmod 0600 "${HOME}/.ssh/authorized_keys"
fi